<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIY1ovmq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIY1ovmq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIY1ovmq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIY1ovmq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIY1ovmq\App_KernelDevDebugContainer([
    'container.build_hash' => 'IY1ovmq',
    'container.build_id' => '63463442',
    'container.build_time' => 1633505075,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIY1ovmq');
