<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI9Gp4Ak\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI9Gp4Ak/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI9Gp4Ak.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI9Gp4Ak\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI9Gp4Ak\App_KernelDevDebugContainer([
    'container.build_hash' => 'I9Gp4Ak',
    'container.build_id' => '5291b84d',
    'container.build_time' => 1633296886,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI9Gp4Ak');
