version: '3.7'
services:
  # initializing db with credential provided by .env file
  db:
    image: mysql:8.0
    container_name: db_docker_symfony
    restart: always
    volumes: 
      - ./db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  # initializing apache and php service with dockerfile
  web:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8741:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always

    #initializing pma service for database managment interface
  pma:
    image: phpmyadmin:5.1-apache
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
       PMA_ARBITRARY : 1
       PMA_HOST : db
       PMA_PORT : 3306
       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

#giving reference to volumes for services
volumes: 
  db-data:
  php:
